# Generated by Django 5.2.6 on 2025-09-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('serving_size', models.DecimalField(decimal_places=2, help_text='Serving size in grams', max_digits=10)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saturated_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unsaturated_fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('micros', models.JSONField(blank=True, default=dict, help_text="Micro nutrients as JSON, e.g., {'vitamin_a': 10.5}")),
                ('meal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomFood',
        ),
    ]
