# Generated by Django 5.2.6 on 2025-09-28 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_rename_micros_food_others_remove_food_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='eaten_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
