# Generated by Django 5.2.6 on 2025-09-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFood',
        ),
    ]
